name: pricely
channels:
  - conda-forge
  - defaults
dependencies:
  - python ==3.11.5
  - pip
  - matplotlib
  - mypy
  - numpy >=2.0
  - scipy
  - scipy-stubs
  - tqdm >=4.66.0
  - types-tqdm
  - cvxopt
  - cvxpy
  - ecos
  - pybind11
  - qdldl-python
  - scs
  - pip:
    - dreal
    - phaseportrait
